# 원래 이 파일은 property 확장자였으나 yml이 조금 더 중복이 적고 계층구조가 확실하게 구분이 돼서 이걸 쓴다.
server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/  
#     컨트롤러가 리턴을 할 때 앞에 붙여주는 경로 변경이다 .
      suffix: .jsp
#     서픽스는 뒤에 붙여주는 경로 변경이다.
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: rud1243
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      #이것은 creat인지 update 인지에 따라 역할이 달라짐 . 테이블 한번 생성되고나서는 update라고 바꿔놔야 추가가 되는 구조다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #엔티티를 만들 때 (테이블 만들때) 변수명 그대로 테이블의 필드값을 넣어주겠다 ! 다른 전략을 쓰면  다른 방식으로 테이블을 만듬  
      use-new-id-generator-mappings: false 
      # 이것의 의미는 jap가 사용하는 넘버링 전략을 사용하지 않는다는 의미! (user클래스에서 제네레이트 밸류를 통해서 아이덴티티 전략으로 갈 것이기 때문 !)
    show-sql: true
    #이것은 sql문 사용 어떻게 했는지 보여주게싿는 으미
    properties:
      hibernate.format_sql: true 
      #이건 예쁘게 정렬해서 나오게

  jackson:
    serialization:
      fail-on-empty-beans: false
    